// export default {
//   vinhos: [
//       {
//         nome: "QUINTA DO CABRIL -  BRANCO VIOSINHO | 2018",
//         image: "/images/v1.png",
//         price: 7.0,
//         rating: 4.5,
//         stock: 5,
//         desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
//         denominacao: "DOURO D.O.C",
//         ano_colheita: "2018",
//         casta: "Viosinho 100%",
//         notas_prova:
//           "Este vinho branco proveniente das zonas mais altas da Quinta, 100% da casta VIOSINHO, apresente grande carácter, complexidade e boa estrutura. Aromas finos e intensos.",
//         sugestao:
//           "Ótimo para acompanhar entradas diversas, carnes brancas e mariscos. Deve ser consumido a uma temperatura entre os 8 e os 10ºC.",
//         analises1: "Alcool 13,00% vol. ",
//         analises2: "Ac.Total 5,40gr/l ",
//         analises3: "Açucar 0,6 g/l ",
//         analises4: "pH 3,27 ",
//         embalagem1: "Garrafa 750ml | ",
//         embalagem2: "Caixa de 6 garrafas | ",
//         embalagem3: "Ean Code: 560 0635793206 | ",
//         embalagem4: "ITF Code: 1 560 0635793203",
//         enologo: "Anselmo Mendes",
//       },
//       {
//         nome: "QUINTA DO CABRIL -  BRANCO VIOSINHO | 2018",
//         image: "/images/v2.png",
//         price: 7.0,
//         rating: 4.5,
//         stock: 5,
//         desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
//         denominacao: "DOURO D.O.C",
//         ano_colheita: "2018",
//         casta: "Viosinho 100%",
//         notas_prova:
//           "Este vinho branco proveniente das zonas mais altas da Quinta, 100% da casta VIOSINHO, apresente grande carácter, complexidade e boa estrutura. Aromas finos e intensos.",
//         sugestao:
//           "Ótimo para acompanhar entradas diversas, carnes brancas e mariscos. Deve ser consumido a uma temperatura entre os 8 e os 10ºC.",
//         analises1: "Alcool 13,00% vol. ",
//         analises2: "Ac.Total 5,40gr/l ",
//         analises3: "Açucar 0,6 g/l ",
//         analises4: "pH 3,27 ",
//         embalagem1: "Garrafa 750ml | ",
//         embalagem2: "Caixa de 6 garrafas | ",
//         embalagem3: "Ean Code: 560 0635793206 | ",
//         embalagem4: "ITF Code: 1 560 0635793203",
//         enologo: "Anselmo Mendes",
//       },
//       {
//         nome: "QUINTA DO CABRIL -  BRANCO VIOSINHO | 2018",
//         image: "/images/v3.png",
//         price: 7.0,
//         rating: 4.5,
//         stock: 5,
//         desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
//         denominacao: "DOURO D.O.C",
//         ano_colheita: "2018",
//         casta: "Viosinho 100%",
//         notas_prova:
//           "Este vinho branco proveniente das zonas mais altas da Quinta, 100% da casta VIOSINHO, apresente grande carácter, complexidade e boa estrutura. Aromas finos e intensos.",
//         sugestao:
//           "Ótimo para acompanhar entradas diversas, carnes brancas e mariscos. Deve ser consumido a uma temperatura entre os 8 e os 10ºC.",
//         analises1: "Alcool 13,00% vol. ",
//         analises2: "Ac.Total 5,40gr/l ",
//         analises3: "Açucar 0,6 g/l ",
//         analises4: "pH 3,27 ",
//         embalagem1: "Garrafa 750ml | ",
//         embalagem2: "Caixa de 6 garrafas | ",
//         embalagem3: "Ean Code: 560 0635793206 | ",
//         embalagem4: "ITF Code: 1 560 0635793203",
//         enologo: "Anselmo Mendes",
//       },
//       {
//         nome: "QUINTA DO CABRIL -  BRANCO VIOSINHO | 2018",
//         image: "/images/v4.png",
//         price: 7.0,
//         rating: 4.5,
//         stock: 5,
//         desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
//         denominacao: "DOURO D.O.C",
//         ano_colheita: "2018",
//         casta: "Viosinho 100%",
//         notas_prova:
//           "Este vinho branco proveniente das zonas mais altas da Quinta, 100% da casta VIOSINHO, apresente grande carácter, complexidade e boa estrutura. Aromas finos e intensos.",
//         sugestao:
//           "Ótimo para acompanhar entradas diversas, carnes brancas e mariscos. Deve ser consumido a uma temperatura entre os 8 e os 10ºC.",
//         analises1: "Alcool 13,00% vol. ",
//         analises2: "Ac.Total 5,40gr/l ",
//         analises3: "Açucar 0,6 g/l ",
//         analises4: "pH 3,27 ",
//         embalagem1: "Garrafa 750ml | ",
//         embalagem2: "Caixa de 6 garrafas | ",
//         embalagem3: "Ean Code: 560 0635793206 | ",
//         embalagem4: "ITF Code: 1 560 0635793203",
//         enologo: "Anselmo Mendes",
//       },
//   ],
// };
