export const SHIPPING_INFO_REQUEST = "SHIPPING_INFO_REQUEST";
export const SHIPPING_INFO_SUCCESS = "SHIPPING_INFO_UCCESS";
export const SHIPPING_INFO_FAIL = "SHIPPING_INFO_FAIL";
export const PAYMENT_METHOD_REQUEST = "PAYMENT_METHOD_REQUEST";
export const PAYMENT_METHOD_SUCCESS = "PAYMENT_METHOD_UCCESS";
export const PAYMENT_METHOD_FAIL = "PAYMENT_METHOD_FAIL";
