export const VINHO_LIST_REQUEST = 'VINHO_LIST_REQUEST';
export const VINHO_LIST_SUCCESS = 'VINHO_LIST_SUCCESS';
export const VINHO_LIST_FAIL = 'VINHO_LIST_FAIL';

export const VINHO_DETAILS_REQUEST = 'VINHO_DETAILS_REQUEST';
export const VINHO_DETAILS_SUCCESS = 'VINHO_DETAILS_SUCCESS';
export const VINHO_DETAILS_FAIL = 'VINHO_DETAILS_FAIL';

export const VINHO_SAVE_REQUEST = 'VINHO_SAVE_REQUEST';
export const VINHO_SAVE_SUCCESS = 'VINHO_SAVE_SUCCESS';
export const VINHO_SAVE_FAIL = 'VINHO_SAVE_FAIL';